FROM autoware-ml

# Install pip dependencies
# https://pypi.org/project/pymoo/
RUN pip install -U pymoo
# Sklearn
RUN pip install -U scikit-learn
# Pandas
RUN pip install pandas
# python-Fire
RUN pip install fire
