
sam2:
    sam2_classes: ["car", "truck", "bus","trailer", "motorcycle", "bicycle", "pedestrian", "road", "vegetation", "tree", "plant", "grass", "bush", "flowerbed", "greenery","cone", "obstacle"]
    background_value: 255
    sam2_checkpoint: "checkpoints/sam2.1_hiera_large.pt"
    sam2_cfg: "sam2/configs/sam2.1/sam2.1_hiera_l.yaml"
    grounding_dino_checkpoint: "gdino_checkpoints/groundingdino_swint_ogc.pth"
    grounding_dino_cfg: "projects/SAM2/grounding_dino/groundingdino/config/GroundingDINO_SwinT_OGC.py"
    box_threshold: 0.30
    text_threshold: 0.25
projective_segmentation:
    invalid_value: 255
    background_value: 0 # this needs to be zero for now
    classes_map: {
        "car" : 1,
        "truck" : 1,
        "bus" : 1,
        "trailer" : 1,
        "motorcycle" : 2,
        "bicycle" : 2,
        "pedestrian" : 3,
        "road" : 4,
        "vegetation" : 5,
        "tree" : 5,
        "plant" : 5,
        "grass" : 5,
        "bush" : 5,
        "flowerbed" : 5,
        "greenery" : 5,
        "cone" : 6,
        "obstacle" : 6
    }
