# WARNING: Running this workflow may incur additional costs in private repositories.
# Please ensure you are aware of the potential charges.
name: Publish autoware-ml Docker image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/tier4/autoware-ml:latest
          ghcr.io/tier4/autoware-ml:${{ github.ref_name }}
