name: Update Database Config

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-database-config:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config_pair:
          - dataset_config_path: "autoware_ml/configs/t4dataset/db_jpntaxi_v3.yaml"
            webauto_keyword: "DBv1.3"
          - dataset_config_path: "autoware_ml/configs/t4dataset/db_j6_v2.yaml"
            webauto_keyword: "DBv3.1"

          # Followings are stale datasets and thus shall not be updated
          # - dataset_config_path: "autoware_ml/configs/t4dataset/db_jpntaxi_v1.yaml"
          #   webauto_keyword: "DBv1.0"
          # - dataset_config_path: "autoware_ml/configs/t4dataset/db_jpntaxi_v2.yaml"
          #   webauto_keyword: "DBv1.1"
          # - dataset_config_path: "autoware_ml/configs/t4dataset/db_gsm8_v1.yaml"
          #   webauto_keyword: "DBv2.0"
          # - dataset_config_path: "autoware_ml/configs/t4dataset/db_j6_v1.yaml"
          #   webauto_keyword: "DBv3.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify config file exists
      run: |
        if [ ! -f ${{ matrix.config_pair.dataset_config_path }} ]; then
          echo "Configuration file not found: ${{ matrix.config_pair.dataset_config_path }}"
          exit 1
        fi

    - name: Setup python3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Setup SSH Keys and known_hosts
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Install dependencies
      run: |
        pip install ruamel.yaml git+ssh://git@github.com/tier4/webauto-auth-py.git

    - name: Decode secretes into json
      env:
        GOOGLE_KEY: ${{ secrets.GOOGLE_JSON_CREDENTIAL }}
        WEBAUTO_AUTH: ${{ secrets.WEBAUTO_AUTH }}
      run: |
        echo -n $GOOGLE_KEY | base64 --decode > google_key.json
        mkdir $HOME/.webauto
        echo -n $WEBAUTO_AUTH | base64 --decode > $HOME/.webauto/auth.toml

    - name: Update database config
      run: |
        python .github/workflows/update_database_list.py \
        --keyword ${{ matrix.config_pair.webauto_keyword }} \
        --config_path ${{ matrix.config_pair.dataset_config_path }} \
        --project_ids prd_jt x2_dev

    - name: Create PR
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: update database config list"
        branch: bot/update-database-config-${{ matrix.config_pair.webauto_keyword }}
        title: "feat: update database configuration for ${{ matrix.config_pair.webauto_keyword }}"
        body: ""
        author: github-actions <github-actions@github.com>
        signoff: true
        delete-branch: true
        add-paths: |
          **/database_*.yaml

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
      shell: bash
